### ISSUE TITLE
Make self-hosting easier

### ISSUE THREAD

**Issue by elie222** [elie222/inbox-zero#383]
People are struggling to get set up atm, so making it as easy possible would help.

Ideally you just set some env vars and it works.
You will need to set up Google, but otherwise we should make it as easy as possible to start.

Improving README in areas where people run into pain points will help. And improved Docker Compose for production.

**Comment by blaine** [comment]
I just found your project (via awesome-mcp), and addressing the bumps in the setup process would be huge. It seems like you've built something really great that's struck a chord!! Well done.

This issue is very timely – I literally opened the github issues here to see if there was some guidance for self-hosting, and this was the first issue I saw.

In my case, I'd ideally like to run this on my Portainer install with Ollama. Both cost of the commercial models and privacy are concerns, and while I'm confident I could get everything running on my laptop or a dev container, having a docker-compose infrastructure that simplifies upgrades and involves only minimal config would be better.

The two issues I've run into are:

1. The UPSTASH_REDIS_TOKEN env var needs to be set. That's a trivial fix; I just generated a random UUIDv4 token and set it in the Portainer stack env vars section.
2. I get the following error: `/data/compose/{x}/apps/web/.env is missing`. This issue is one I can't get past easily with Portainer specifically. My main option (afaik; I'm far from a docker expert) is to fork the docker-compose.yml and include a COPY directive or a custom mount point, but that would mean losing easy/automated upgrades. I think (?) the ideal fix here is to fix the web app so that it doesn't depend on the existence of the .env file, but instead uses environment variables provided in the stack config.

The issue I'm _expecting_ to run into once I've gotten past the above is that the docker-compose currently doesn't include Ollama. This is easy to fix, but again requires forking the docker-compose. I'd probably start with this: https://github.com/mythrantic/ollama-docker

Unfortunately, I don't really have cycles to do a fork and get all this working, or to set up all this by hand on a dev container (my ultimate goal here is to do a one-time install and hit the ground running – email overload is real! ❤️😂), but I'm very happy to help test fixes and provide feedback/screenshots/loom recordings if that's helpful at all.

**Comment by sagararyal** [comment]
Really cool project. I managed to get it up and running on **Coolify**, and while it’s working decently now, I have a few thoughts:

It’d be great if we could have a **published Docker image** for the project.

### 1. Run Docker in Prod Mode  
The Docker container currently runs the app in development mode. I tried modifying it to run in production, but it required spinning up too many services and setting a bunch of environment variables.  
I had a similar experience when trying to deploy it on Vercel — the setup just felt a bit heavy.

### 2. Simplifying the Setup  
To make deployments easier, I’d like to suggest introducing a new environment variable, something like:

```env
INBOX_ZERO_MANAGED=false
```
- When set to `false`, this mode would reduce the required environment variables to just the essentials: **DB**, **REDIS**, and **Google** credentials.
- By default, this could be set to `false` for self-hosted and development builds, ensuring flexibility for advanced setups like your hosted setup.
- When set to `false`, auto create a row in `Premium` table, during user signup, with features set to UNLOCKED. (If the premium features are intended to be available for self hosted instances)

### 3. OpenAI-Compatible API  
Would it make sense to switch to an OpenAI-compatible API instead of integrating Ollama separately?  
We could create a new provider type — **OpenAI-Compatible** — that collects the **URL** and **token**, and simply passes them to the existing OpenAI controllers.

--
For anyone trying on Coolify, I deployed Redis and Postgres separately and passed the URLs.
https://github.com/elie222/inbox-zero/compare/main...Plant-for-the-Planet-org:inbox-zero:deploy

Below is bare minimum of required environments with Ollama

```
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_ENCRYPT_SALT= # gen with openssl rand -hex 32
GOOGLE_ENCRYPT_SECRET= #openssl rand -hex 16
GOOGLE_PUBSUB_TOPIC_NAME=
NEXTAUTH_SECRET= #openssl rand -hex 16
NEXTAUTH_URL=
NEXT_PUBLIC_OLLAMA_MODEL=
OLLAMA_BASE_URL=
DATABASE_URL=
REDIS_URL=
UPSTASH_REDIS_TOKEN=#openssl rand -hex 16
```

**Comment by vkuprin** [comment]
For anyone struggling with self-hosting, I managed to get Inbox Zero working on Coolify https://coolify.io/ with this Docker Compose setup. Instead of dealing with complex secrets management, you can use this simplified approach:

```yaml
version: '3.8'

services:
  inbox-zero:
    image: node:22-alpine
    container_name: inbox-zero-app
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "
        echo 'Installing dependencies...' &&
        apk update && apk add --no-cache git netcat-openbsd &&
        rm -rf /app/* /app/.* 2>/dev/null || true &&
        git clone https://github.com/elie222/inbox-zero.git /tmp/inbox-zero &&
        cp -r /tmp/inbox-zero/* /app/ &&
        cp -r /tmp/inbox-zero/.* /app/ 2>/dev/null || true &&
        rm -rf /tmp/inbox-zero &&
        npm install -g pnpm &&
        cd /app && pnpm install &&
        echo 'Waiting for database...' &&
        while ! nc -z inbox-db 5432; do sleep 2; done &&
        cd /app/apps/web &&
        export DATABASE_URL='postgresql://postgres:postgres@inbox-db:5432/inboxzero' &&
        export DIRECT_URL='postgresql://postgres:postgres@inbox-db:5432/inboxzero' &&
        npx prisma migrate dev --skip-generate --name init &&
        cd /app && pnpm build &&
        cd /app/apps/web && npx next start -p 3000 -H 0.0.0.0
      "
    environment:
      # Database
      DATABASE_URL: "postgresql://postgres:postgres@inbox-db:5432/inboxzero"
      DIRECT_URL: "postgresql://postgres:postgres@inbox-db:5432/inboxzero"
      
      # Auth (Generate with openssl rand -hex 32)
      NEXTAUTH_SECRET: "***YOUR_RANDOM_SECRET_HERE***"
      NEXTAUTH_URL: "https://your-domain.com"
      AUTH_TRUST_HOST: "true"
      
      # Google OAuth (Get from Google Cloud Console)
      GOOGLE_CLIENT_ID: "***YOUR_GOOGLE_CLIENT_ID***"
      GOOGLE_CLIENT_SECRET: "***YOUR_GOOGLE_CLIENT_SECRET***"
      GOOGLE_ENCRYPT_SECRET: "***RANDOM_32_CHAR_HEX***"  # openssl rand -hex 32
      GOOGLE_ENCRYPT_SALT: "***RANDOM_16_CHAR_HEX***"    # openssl rand -hex 16
      
      # Redis
      REDIS_URL: "redis://inbox-redis:6379"
      KV_URL: "redis://inbox-redis:6379"
      UPSTASH_REDIS_URL: ""  # Leave empty for local Redis
      UPSTASH_REDIS_TOKEN: ""  # Leave empty for local Redis
      
      # OpenAI (Optional - for AI features)
      OPENAI_API_KEY: "***YOUR_OPENAI_KEY***"
      
      # Admin users (your email)
      ADMINS: "your-email@domain.com"
      
      # Production settings
      NODE_ENV: "production"
      
      # Minimal required settings (can be dummy values for self-hosted)
      GOOGLE_PUBSUB_TOPIC_NAME: "inbox-zero-topic"
      INTERNAL_API_KEY: "local-dev-internal-key"
      QSTASH_CURRENT_SIGNING_KEY: "local-dev-signing-key"
      QSTASH_NEXT_SIGNING_KEY: "local-dev-next-signing-key"
      QSTASH_URL: ""
      QSTASH_TOKEN: ""
    ports:
      - "3000:3000"
    depends_on:
      inbox-db:
        condition: service_healthy
      inbox-redis:
        condition: service_started
    networks:
      - inbox-network

  inbox-db:
    image: postgres:17-alpine
    container_name: inbox-zero-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inboxzero
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - inbox-postgres-data:/var/lib/postgresql/data
    networks:
      - inbox-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  inbox-redis:
    image: redis:7-alpine
    container_name: inbox-zero-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - inbox-redis-data:/data
    networks:
      - inbox-network

volumes:
  inbox-postgres-data:
    driver: local
  inbox-redis-data:
    driver: local

networks:
  inbox-network:
    driver: bridge
```

## Key Points:

1. **No .env file required** - Everything is passed as environment variables
2. **Local Redis instead of Upstash** - Eliminates external dependencies
3. **Simplified secrets** - Generate using `openssl rand -hex 32` and `openssl rand -hex 16`

## Required Setup Steps:

1. **Google Cloud Console:**
   - Enable People API and Gmail API
   - Set redirect URI: `https://your-domain.com/api/auth/callback/google`
   - Get CLIENT_ID and CLIENT_SECRET

2. **Generate secrets:**
   ```bash
   openssl rand -hex 32  # For NEXTAUTH_SECRET and GOOGLE_ENCRYPT_SECRET
   openssl rand -hex 16  # For GOOGLE_ENCRYPT_SALT
   ```

**Comment by sla-te** [comment]
I don't see, that self hosting outside of vercel is possible without this getting addressed first https://github.com/elie222/inbox-zero/issues/673

**Comment by ThibautGrx** [comment]
Hi, I’ve opened a draft PR here: https://github.com/elie222/inbox-zero/pull/760 about how to deploy on vps using docker, nginx and let's encrypt.
I’m sure there are several things that can be improved, but I thought it might be useful to share it early to get some feedback.

**Comment by luisalrp** [comment]
Hi!

I’m trying to get the deployment up and running on Coolify. Below is the Docker Compose file I’m using. It’s not working yet, but it feels like I’m very close to getting it right:
```
name: inbox-zero-services
services:
  db:
    image: postgres
    restart: always
    container_name: inbox-zero
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER:-postgres}'
      - 'POSTGRES_DB=${POSTGRES_DB:-inboxzero}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}'
    volumes:
      - 'database-data:/var/lib/postgresql/data/'
    # ports:
    #  - '${POSTGRES_PORT:-5432}:5432'
    networks:
      - inbox-zero-network
    healthcheck:
      test: 'pg_isready -U ${PG_DATABASE_USER:-postgres} -h localhost -d postgres'
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis
    # ports:
    #  - '${REDIS_PORT:-6380}:6379'
    volumes:
      - 'database-data:/data'
    networks:
      - inbox-zero-network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 5s
      timeout: 5s
      retries: 10
  serverless-redis-http:
    ports:
      - '${REDIS_HTTP_PORT:-8079}:80'
    image: 'hiett/serverless-redis-http:latest'
    environment:
      SRH_MODE: env
      SRH_TOKEN: '${UPSTASH_REDIS_TOKEN}'
      # SRH_CONNECTION_STRING: 'redis://redis:6379'
      SRH_CONNECTION_STRING: 'redis://redis:6380'
    networks:
      - inbox-zero-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  web:
    # image: 'ghcr.io/elie222/inbox-zero:latest'
    # pull_policy: if_not_present
    build:
      context: 'https://github.com/elie222/inbox-zero.git'
      dockerfile: docker/Dockerfile.prod
      args:
        NEXT_PUBLIC_BASE_URL: '${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}'
    depends_on:
      - db
      - redis
    networks:
      - inbox-zero-network
    environment:
      DATABASE_URL: 'postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-inboxzero}?schema=public'
      DIRECT_URL: 'postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-inboxzero}?schema=public'
      UPSTASH_REDIS_URL: 'http://serverless-redis-http:80'
      UPSTASH_REDIS_TOKEN: '${UPSTASH_REDIS_TOKEN}'
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
volumes:
  database-data: null
networks:
  inbox-zero-network: null
```
I’m running into the following errors — maybe someone knows how to resolve them:
```
Pulling images.
 serverless-redis-http Pulling 
 web Skipped - No image to be pulled 
 redis Pulling 
 db Pulling 
 db Pulled 
 serverless-redis-http Pulled 
 redis Pulled 
Creating Docker network.
Starting service.
#1 [internal] load local bake definitions
#1 reading from stdin 636B done
#1 DONE 0.0s

#2 [internal] load git source https://github.com/elie222/inbox-zero.git
#2 0.563 ref: refs/heads/main	HEAD
#2 0.563 cc4896b5c98c8a1d8a08e8f314ebc88c31460efa	HEAD
#2 1.027 cc4896b5c98c8a1d8a08e8f314ebc88c31460efa	refs/heads/main
#2 0.520 ref: refs/heads/main	HEAD
#2 0.520 cc4896b5c98c8a1d8a08e8f314ebc88c31460efa	HEAD
#2 1.316 fatal: No url found for submodule path 'apps/web/app/(marketing)' in .gitmodules
#2 ERROR: failed to update submodules for https://github.com/elie222/inbox-zero.git: git stderr:
fatal: No url found for submodule path 'apps/web/app/(marketing)' in .gitmodules
: exit status 128
------
 > [internal] load git source https://github.com/elie222/inbox-zero.git:
0.563 ref: refs/heads/main	HEAD
0.563 cc4896b5c98c8a1d8a08e8f314ebc88c31460efa	HEAD
1.027 cc4896b5c98c8a1d8a08e8f314ebc88c31460efa	refs/heads/main
0.520 ref: refs/heads/main	HEAD
0.520 cc4896b5c98c8a1d8a08e8f314ebc88c31460efa	HEAD
1.316 fatal: No url found for submodule path 'apps/web/app/(marketing)' in .gitmodules
------
failed to solve: failed to read dockerfile: failed to update submodules for https://github.com/elie222/inbox-zero.git: git stderr:

fatal: No url found for submodule path 'apps/web/app/(marketing)' in .gitmodules

: exit status 128
```
Thanks!!
